baseURL = 'https://timiGao.github.io/'
locale = 'zh-cn'
title = "Timi's Site"
theme = 'PaperMod'
defaultContentLanguage = "zh"
languageCode = 'zh'
hasCJKLanguage = true  # <--- 开启中日韩语言精准字数统计

# 开启 HTML 渲染权限（不仅能用来插入头像，也能让文章支持 <details> 折叠框）
[markup.goldmark.renderer]
  unsafe = true

# ================= 顶部导航栏 (Menu) =================
[[menu.main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 20

# ================= 基础参数 (Params) =================
[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = false
  ShowToc = true   # 全局默认给所有文章开启目录功能
  TocOpen = true   # 全局默认让目录保持展开状态

  # ================= 社交媒体链接 =================
  # 必须写在 params 之下，并在 assets 等子节点之上
  socialIcons = [
    { name = "github", url = "https://github.com/timiGao" },
    { name = "email", url = "mailto:timi.ghm@outlook.com" },
    { name = "bilibili", url = "https://space.bilibili.com/402601923" },
    { name = "zhihu", url = "https://www.zhihu.com/people/ti-mi-19-68" },
    { name = "douban", url = "https://www.douban.com/people/278279045" },
    { name = "bangumi", url = "https://bgm.tv/user/timi" },
    { name = "Steam", url = "https://steamcommunity.com/profiles/76561199885630445/" }
  ]

# ================= 网站图标 (Favicon) =================
[params.assets]
  favicon = "/apple-touch-icon.png"
  apple_touch_icon = "/apple-touch-icon.png"

# ================= 首页顶部信息 (Home Info) =================
[params.homeInfoParams]
  Title = "Hi, 我是 Timi"
  Content = """
  <style>
    .home-info { text-align: center; }
    .home-info .social-icons { justify-content: center; }
  </style>
  <img src="/images/avatar.jpg" alt="avatar" width="90" style="border-radius: 50%; margin-bottom: 15px; display: block; margin-left: auto; margin-right: auto;">
  """