baseURL = 'https://timiGao.github.io/'
languageCode = 'zh-cn'
title = "Timi's Site"
theme = 'PaperMod'

# ================= 顶部导航栏 (Menu) =================
[[menu.main]]
  identifier = "posts"
  name = "文章"
  url = "/posts/"
  weight = 10

[[menu.main]]
  identifier = "about"
  name = "关于"
  url = "/about/"
  weight = 20

# ================= 基础参数 (Params) =================
[params]
  defaultTheme = "auto"
  ShowReadingTime = true
  ShowShareButtons = true

# ================= 网站图标 (Favicon) =================
[params.assets]
  favicon = "/apple-touch-icon.png"
  apple_touch_icon = "/apple-touch-icon.png"

# ================= 首页顶部信息 (Home Info) =================
[params.homeInfoParams]
  Title = "Hi, 我是 Timi"
  Content = "电子科技大学 CS 学生"

# ================= 社交媒体链接 (Social Icons) =================
[[params.socialIcons]]
  name = "github"
  url = "https://github.com/timiGao"

[[params.socialIcons]]
  name = "email"
  url = "mailto:timi.ghm@outlook.com"